### ISSUE TITLE
Problem reaching the price calculator API URL

### ISSUE THREAD

**Issue by bri-git00** [talkpython/twilio-and-sendgrid-python-course#1]
Hello - Today I was working on the lesson to calculate the cake price, and the the API for this does not seem to be working.  I believe I have the URL correct, I have triple checked, but maybe I am still missing something or it is not available at the moment.  The URL I am using is as follows:

https://cloudcitycakecompany.azurewebsites.net/api/pricecalculator

I have tried to reach it on its own, and when I do I see this.  

This page isn’t workingcloudcitycakecompany.azurewebsites.net is currently unable to handle this request.
HTTP ERROR 500

However, I still did try to call through Twilio Studio as per the course and I received an error.

I apologize if I am just missing something, but again I have tried to search for other reports and do not see this being raised as far as I can tell.

Thanks,
-Brian

**Comment by bri-git00** [comment]
Apologies - I have hard-coded the value and the API does work so I must have a problem with my Twilio HTTP request

**Comment by mikeckennedy** [comment]
Glad you caught the problem.

Best,
Michael

Sent via Superhuman iOS ***@***.***>
